---
- name: ansible with tasks and condition with loop
  hosts: websrv
  tasks:
    - name: Run the tasks with_item 
      command: echo "{{ item }}"
      loop: [0, 2, 4, 6, 8, 10]
      when: item > 5
