---
- name: This is the first demo for loop
  hosts: websrv,database
  tasks:
   - name: Installation of my apache webserver stack 
     yum:
      name: "{{ item }}"
      state: present
     with_items:
      - vsftpd
      - tree
      - git
      - mysql
