---
- name: User creation on the Linux based server
  hosts: websrv
  gather_facts: false
  tasks:
    - name: angleone user creations
      user: 
        name: angel7
        state: present
        uid: 6090
        group: root
      register: output
#      debug:
#        msg: "this is my task-1"
    
#    - name: This is my output
#      debug:
#        msg: "{{ output }}"
